name: Bug Report
description: Report a bug or issue with the GitHub Backup Tool
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the GitHub Backup Tool are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug or issue you encountered
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen instead
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run command...
        2. Set environment variable...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output (remember to remove sensitive information like tokens)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your configuration (remove sensitive information)
      placeholder: |
        Command used: github-backup backup-all
        Environment variables: GITHUB_TOKEN=set, DROPBOX_ACCESS_TOKEN=set
        CLI flags: --backup-folder /Projects

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have removed sensitive information (tokens, usernames, etc.)
          required: true
        - label: I am using the latest version of the tool
          required: false
